// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWindow():Promise<void>;

export function DefaultFolder():Promise<string>;

export function Delete(arg1:Array<main.FileEntry>):Promise<main.DeleteResult>;

export function IsWatching():Promise<boolean>;

export function MaximiseWindow():Promise<void>;

export function MinimiseWindow():Promise<void>;

export function PickFolder():Promise<string>;

export function Scan(arg1:string,arg2:boolean):Promise<Array<main.FileEntry>>;

export function StartWatch(arg1:string,arg2:boolean):Promise<boolean>;

export function StopWatch():Promise<void>;
