// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DefaultFolder() {
  return window['go']['main']['App']['DefaultFolder']();
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function IsWatching() {
  return window['go']['main']['App']['IsWatching']();
}

export function MaximiseWindow() {
  return window['go']['main']['App']['MaximiseWindow']();
}

export function MinimiseWindow() {
  return window['go']['main']['App']['MinimiseWindow']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function Scan(arg1, arg2) {
  return window['go']['main']['App']['Scan'](arg1, arg2);
}

export function StartWatch(arg1, arg2) {
  return window['go']['main']['App']['StartWatch'](arg1, arg2);
}

export function StopWatch() {
  return window['go']['main']['App']['StopWatch']();
}
